---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: get_templates_based_on_selected_os_and_location_and_environment
    inherits: 
    description: 
  fields:
  - execute:
      value: get_templates_based_on_selected_os_and_location_and_environment
