---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: get_lifecycle_environment_names_filtered_by_tags
    inherits: 
    description: 
  fields:
  - execute:
      value: get_lifecycle_environments_filtered_by_tags( return_key => 'name' )
