---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: satellite
    inherits: 
    description: 
  fields:
  - AcquireIPAddress:
      value: "/Integration/Satellite/Operations/Methods/AcquireIPAddress"
  - ReleaseIPAddress:
      value: "/Integration/Satellite/Operations/Methods/ReleaseIPAddress"
