---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: Provision VM using Satellite
    name: satellite
    inherits: 
    description: 
  fields:
  - Provision:
      value: "/Infrastructure/VM/Provisioning/StateMachines/Methods/Provision"
  - CheckProvisioned:
      value: "/Infrastructure/VM/Provisioning/StateMachines/Methods/CheckProvisioned"
  - AddToService:
      value: "/Infrastructure/VM/Provisioning/StateMachines/Methods/AddVMToService"
  - RegisterSatellite:
      value: "/Integration/Satellite/Operations/Methods/RegisterSatellite"
  - StartVM:
      value: "/Infrastructure/VM/Provisioning/StateMachines/Methods/StartVM"
  - CheckSatelliteBuildCompleted:
      value: "/Integration/Satellite/Operations/Methods/CheckSatelliteBuildCompleted"
